development:
  adapter: postgresql
  encoding: unicode
  database: presspass_development
  pool: 5
  username: vswamy
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: presspass_test
  pool: 5
  username: vswamy
  password: 